Better responsive images
django-cms/djangocms-picture pull request #114
Opened 2022-05-10 23:02 UTC by fabien-michel

## Description

Rewrote of responsive images mode which now make use of `<picture>` HTML tag to support different pictures for small, medium and large screens and to allow to generate WebP alternative version.

User can now setup a specific optional alternative images for medium and large screen (small is the default one)
User can also specify optional viewport width (vw) for each alternative in order to help browser choose better version.
The plugin can now generate a WebP alternative version for each alternative in each size.

I've renamed two settings:
-   `DJANGOCMS_PICTURE_RESPONSIVE_IMAGES` (enable responsive mode default value) become `DJANGOCMS_PICTURE_RESPONSIVE_IMAGES_ENABLED` 
-   `DJANGOCMS_PICTURE_RESPONSIVE_IMAGES_VIEWPORT_BREAKPOINTS`  (image sizes versions to generate)  become `DJANGOCMS_PICTURE_RESPONSIVE_IMAGES_SIZES`

There is new settings :
- `DJANGOCMS_PICTURE_RESPONSIVE_IMAGES_BREAKPOINT_MEDIUM` size of medium screen breakpoint. Default to `768`
- `DJANGOCMS_PICTURE_RESPONSIVE_IMAGES_BREAKPOINT_LARGE` size of large screen breakpoint. Default to `992`
- `DJANGOCMS_PICTURE_RESPONSIVE_IMAGES_ALTERNATIVE_FORMAT_WEBP` generate WebP version. Default to `False`

## Related resources

## Checklist

* [x] I have opened this pull request against ``master``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

2022-07-29 08:15 UTC, fabien-michel commented
What are the next steps about this PR ?
Have theses evolutions a place in djangocms-picture ?
If yes, are the proposed modifications acceptable or need changes ?
If no, should it be better to propose a fork (djangocms-picture-responsive) with this specific enhancement ?

May be it could be nice to talk about it with someone.

2022-07-29 13:59 UTC, marksweb commented
@fabien-michel We've actually just been talking about this in one of our meetings. We have a meeting at 2pm UK time every other Friday. You're welcome to join, or post in the technical-committee or workgroup-pr-review channels on our slack; https://django-cms.org/slack

I don't use this app, so I've not commented on here. But hopefully with some visibility on slack, we might find some people who do use it & who can review this.

2022-10-08 11:01 UTC, marksweb requested changes
This review is taking me a while but here's some improvements to the docs

2022-10-08 11:01 UTC, marksweb commented on CHANGELOG.rst
> +Incoming
```suggestion
Unreleased
```

2022-10-08 11:01 UTC, marksweb commented on CHANGELOG.rst
> +* Rewrote of responsive images mode which now make use of ``<picture>`` HTML tag
```suggestion
* Rewrite of responsive images mode, which now makes use of the ``<picture>`` HTML tag
```

2022-10-08 11:01 UTC, marksweb commented on CHANGELOG.rst
> +  allow to generate WebP alternative version.
```suggestion
  allow the generation of a WebP alternative version.
```

2022-10-08 11:01 UTC, marksweb commented on README.rst
> +Therefore, the plugin accept 2 alternatives pictures for medium and large screen (small being the default picture).
```suggestion
Therefore, the plugin accepts 2 alternative pictures, for medium and large screens (small being the default picture). 
```

2022-10-08 11:01 UTC, marksweb commented on README.rst
> +`Pillow require <https://pillow.readthedocs.io/en/stable/installation.html#external-libraries>` the libwebp library to be installed on the host system.
```suggestion
`Pillow requires <https://pillow.readthedocs.io/en/stable/installation.html#external-libraries>` the libwebp library to be installed on the host system.
```

2023-04-04 09:54 UTC, i-salameh95 commented
I think this PR is so important, I was working on page insight for my website, and one of the suggestions is to use responsive images, I have use the settings by djangocms-picture provided OTB but another suggest said that: 
The size of the image doesn’t match the sizes attribute (max-width: 576px) 576px, (max-width: 768px) 768px, (max-width: 992px) 992px, 1000px. At a viewport of 320x427 the image was 294 pixels wide instead of the specified 576 (-49% difference). The affected viewports are 300x169-540x720, 580x326-740x987, 780x439-940x1253.

**_Try using sizes="(min-width: 1080px) 1000px, 95.53vw" instead._**
... that's why I search for this.

2023-06-24 18:15 UTC, marksweb requested changes

2023-06-24 18:15 UTC, marksweb commented on .github/workflows/publish-to-test-pypi.yml
> +      - better_responsive_images
Please revert this.

2023-06-25 19:36 UTC, fabien-michel commented
Sorry, I was trying to make a fork and still have this PR alive.
I think the changes this PR adds make the UI more complex. It is hard for our editors here to understand how the responsiveness works and also how the image selection works according to screen size. 
So I think the work done in this PR needs to be "rethought" to a simpler UI before it would be nice to have it in djangocms-picture. 
I intend to make a new package "djangocms-picture-responsive" which contains this PR and I will try to maintain it. That's why I changed the branch name in ci config . 
Since it interferes too much with PR, I think it's better to close this PR for now.
Thanks for your time.

2023-06-25 19:36 UTC, closed without merging